#!/bin/sh
# === MESH 6G PARTE 1 ===

. /lib/functions.sh
. /lib/functions/network.sh

band_steer_helper=${band_steer_helper:-none}

band_steer_helper_switch()
{
	if [ "$band_steer_helper" = "usteer" ]; then
		uci delete usteer.@usteer[0].event_log_types 2>/dev/null
		uci delete usteer.@usteer[0].ssid_list 2>/dev/null
		uci commit usteer
		test -x /etc/init.d/dawn && {
			/etc/init.d/dawn enabled && /etc/init.d/dawn disable
			/etc/init.d/dawn running && /etc/init.d/dawn stop
		}
		test -x /etc/init.d/usteer && {
			/etc/init.d/usteer enabled || /etc/init.d/usteer enable
			/etc/init.d/usteer running || /etc/init.d/usteer start
		}
	elif [ "$band_steer_helper" = "dawn" ]; then
		test -x /etc/init.d/usteer && {
			/etc/init.d/usteer enabled && /etc/init.d/usteer disable
			/etc/init.d/usteer running && /etc/init.d/usteer stop
		}
		test -x /etc/init.d/dawn && {
			/etc/init.d/dawn enabled || /etc/init.d/dawn enable
			/etc/init.d/dawn running || /etc/init.d/dawn start
		}
	else
		test -x /etc/init.d/dawn && {
			/etc/init.d/dawn enabled && /etc/init.d/dawn disable
			/etc/init.d/dawn running && /etc/init.d/dawn stop
		}
		test -x /etc/init.d/usteer && {
			/etc/init.d/usteer enabled && /etc/init.d/usteer disable
			/etc/init.d/usteer running && /etc/init.d/usteer stop
		}
	fi
}

[ "x$1" = "xband_steer_helper_switch" ] && {
	band_steer_helper_switch
	exit 0
}

[ "x$1" = "xsetup" ] && {
	exit 0
}

config_load fakemesh

config_get_bool enabled default 'enabled' '0'

test $enabled -eq 0 && {
	rm -f /www/fakemesh.*
	rm -rf /tmp/fakemesh_lck*
	rm -f /tmp/fakemesh.firewall.include

	test -e /etc/init.d/umdns && {
	rm /tmp/fakemesh.umdns.json 2>/dev/null && \
	/etc/init.d/umdns restart
	}

	uci delete wireless.meshx0 &>/dev/null
	uci delete wireless.meshx1 &>/dev/null
	uci delete wireless.meshx2 &>/dev/null

	I=0
	while uci get wireless.@wifi-iface[$I] &>/dev/null; do
		echo "$(uci get wireless.@wifi-iface[$I].network)" | grep -q "^meshx" && {
			uci set wireless.@wifi-iface[$I].network="lan"
		}
		I=$((I+1))
	done

	uci delete fakemesh.default.wifim_md5 &>/dev/null
	uci delete dhcp.meshx0 &>/dev/null
	uci delete dhcp.meshx2 &>/dev/null
	uci delete network.meshx0 &>/dev/null
	uci delete network.meshx2 &>/dev/null
	uci delete network.meshx0_6 &>/dev/null
	uci delete network.meshx2_6 &>/dev/null
	uci delete firewall.fakemesh &>/dev/null
	sed -i "/.* controller.fakemesh/d" /etc/hosts
	sed -i "/sh \/usr\/share\/fakemesh\/firewall.include.*/d" /etc/firewall.include

	uci delete network.lan.auto &>/dev/null
	uci delete network.wan.auto &>/dev/null
	uci delete network.wan6.auto &>/dev/null

	lan_idx=0
	while uci get network.@device[$lan_idx] &>/dev/null && [ $(uci get network.@device[$lan_idx].name) != "br-lan" ]; do lan_idx=$((lan_idx+1)); done
	lan_ports="$(uci get network.@device[$lan_idx].ports 2>/dev/null)"
	wan_port="$(uci get network.wan.device 2>/dev/null)"
	newlan_ports=$(for lp in $lan_ports; do [ "$lp" = "$wan_port" ] || echo $lp; done | sort | uniq)
	newlan_ports=$(echo $newlan_ports)
	[ "$lan_ports" != "$newlan_ports" ] && {
		uci delete network.@device[$lan_idx].ports &>/dev/null
		for lp in $newlan_ports; do
			uci add_list network.@device[$lan_idx].ports="$lp"
		done
	}

	lan_idx=0
	while uci get firewall.@zone[$lan_idx] &>/dev/null && [ $(uci get firewall.@zone[$lan_idx].name) != "lan" ]; do lan_idx=$((lan_idx+1)); done
	lan_net="$(uci get firewall.@zone[$lan_idx].network 2>/dev/null)"
	newlan_net=$(for ln in $lan_net; do [ "$ln" = "meshx0" -o "$ln" = "meshx0_6" -o "$ln" = "meshx2" -o "$ln" = "meshx2_6" ] || echo $ln; done | sort | uniq)
	newlan_net=$(echo $newlan_net)
	[ "$lan_net" != "$newlan_net" ] && {
		uci delete firewall.@zone[$lan_idx].network &>/dev/null
		for ln in $newlan_net; do
			uci add_list firewall.@zone[$lan_idx].network="$ln"
		done
		uci commit firewall
	}

	uci changes

	uci commit fakemesh
	uci commit wireless
	uci commit dhcp
	uci commit firewall
	uci commit network
	/etc/init.d/network reload
	/etc/init.d/dnsmasq reload
	/etc/init.d/firewall reload &>/dev/null
	exit 0
}

config_get role default 'role' 'agent'
config_get band default 'band' '5g'
config_get Xid default 'id'
config_get Xkey default 'key'
config_get access_ip default 'access_ip' '10.10.10.1'
config_get sync_ac default 'sync_ac' '1'
config_get fronthaul_disabled default 'fronthaul_disabled' '0'

lost_ac=${lost_ac:-0}
LOST_AC_CNT=3

# === FIN MESH 6G PARTE 1 ===

# === MESH 6G PARTE 2 ===

agent_lost_ac()
{
	[ "$role" = "agent" ] || [ "$role" = "wap" ] || return 0

	pid=$$
	logger -t fakemesh "agent_lost_ac($pid): started! lost_ac=$lost_ac"

	if test $lost_ac -gt $LOST_AC_CNT; then
		rm -rf /tmp/fakemesh_lck3
		lost_ac=$lost_ac exec /usr/sbin/fakemesh agent_sync_config &
		return 0
	fi

	uci delete network.lan.auto &>/dev/null
	uci set network.lan.ipaddr="192.168.16.1"
	for lip in `seq 16 20`; do
		if ip route | grep -q "192.168.$lip.0/"; then
			:
		else
			uci set network.lan.ipaddr="192.168.$lip.1"
			break
		fi
	done
	uci set network.lan.netmask='255.255.255.0'
	logger -t fakemesh "agent_lost_ac($pid): setup temporary lan ip=$(uci get network.lan.ipaddr)"

	ssid="$(uci get base_config.@status[0].SSID)@$(uci get network.lan.ipaddr)"
	ssid_passwd=$(uci get base_config.@status[0].SSID_PASSWD)
	K=0
	for band in 2g 5g 6g; do
		wbandstr=$(uci show wireless | grep .band=\'${band}\'$ -m1)
		if test -n "$wbandstr"; then
			radio=$(echo $wbandstr | cut -d\. -f2)

			uci set wireless.wifinet$K=wifi-iface
			uci set wireless.wifinet$K.device="${radio}"
			uci set wireless.wifinet$K.network='lan'
			uci set wireless.wifinet$K.mode='ap'
			uci set wireless.wifinet$K.ssid="${ssid}"
			uci set wireless.wifinet$K.encryption="psk2"
			uci set wireless.wifinet$K.key="${ssid_passwd}"
			uci set wireless.wifinet$K.wpa_group_rekey='601'
			uci set wireless.wifinet$K.max_inactivity='301'
			if uci get wireless.${radio}.path | grep -q bcma || iwinfo wlan${radio:5} info | grep -qi Cypress; then
				WLAN_IDX=${radio:5}
				uci set wireless.wifinet$K.ifname="wlan${WLAN_IDX}"
			else
				uci set wireless.wifinet$K.ieee80211r='1'
				uci set wireless.wifinet$K.ft_over_ds='0'
				uci set wireless.wifinet$K.ft_psk_generate_local='1'
			fi

			uci delete wireless.wifinet$K.disabled 2>/dev/null
			K=$((K+1))
			logger -t fakemesh "agent_lost_ac($pid): starting wifi SSID=\'${ssid}\' on ${radio} $band!"
		fi
	done
	while uci get wireless.wifinet$K 2>/dev/null; do
		uci set wireless.wifinet$K.disabled='1'
		K=$((K+1))
	done

	nft_add_brmeshfilters() {
		brif="$1"
		nft add table netdev brmeshfilters_$brif 2>/dev/null
		nft "add chain netdev brmeshfilters_$brif devfilter { type filter hook ingress device $brif priority 0 ; }" 2>/dev/null
		nft add rule netdev brmeshfilters_$brif devfilter udp sport 68 drop 2>/dev/null
	}

	for brif in $(cd /sys/class/net/br-lan/brif/ && ls); do
		iwinfo $brif info &>/dev/null && [ "$brif" != "meshx0" ] && [ "$brif" != "meshx1" ] && [ "$brif" != "meshx2" ] && continue
		nft_add_brmeshfilters $brif
	done

	uci add_list dhcp.lan.dhcp_option='option:router'
	uci add_list dhcp.lan.dhcp_option='6'

	/etc/init.d/network reload
	/etc/init.d/dnsmasq reload
	sleep 5
	uci revert dhcp
	uci revert network
	uci revert wireless

	for brif in $(cd /sys/class/net/br-lan/brif/ && ls); do
		iwinfo $brif info &>/dev/null && [ "$brif" != "meshx0" ] && [ "$brif" != "meshx1" ] && [ "$brif" != "meshx2" ] && continue
		nft_add_brmeshfilters $brif
	done

	logger -t fakemesh "agent_lost_ac($pid): done!"

	rm -rf /tmp/fakemesh_lck3
	lost_ac=$lost_ac exec /usr/sbin/fakemesh agent_sync_config &
}

# === FIN MESH 6G PARTE 2 ===

# === MESH 6G PARTE 3 ===

# Aquí continuarías con el resto del script, por ejemplo:
agent_sync_config()
{
	# ... toda la función original, NO ALTERADA ...
}

agent_keep_alive()
{
	# ... toda la función original, NO ALTERADA ...
}

agent_fix_channel()
{
	# ... toda la función original, NO ALTERADA ...
}

[ "x$1" = "xagent_lost_ac" ] && {
	agent_lost_ac
	exit 0
}
[ "x$1" = "xagent_fix_channel" ] && {
	agent_fix_channel
	exit 0
}
[ "x$1" = "xagent_keep_alive" ] && {
	agent_keep_alive
	exit 0
}
[ "x$1" = "xagent_sync_config" ] && {
	agent_sync_config
	exit 0
}
[ "x$1" = "xgen_config" ] && {
	# http://controller.fakemesh/fakemesh.435ca8a686ae9f07eb4eb67d2216b154
	[ "$role" = "controller" ] && {
		hash=$(echo -n ${Xid}${Xkey} | md5sum | head -c32)
		ln -s /etc/config/fakemesh /www/fakemesh.$hash 2>/dev/null
		for f in $(ls /www/fakemesh.*); do
			[ "$f" != "/www/fakemesh.$hash" ] && rm -f "$f"
		done
	}
	exit 0
}

test -n "${Xid}" || {
	exit 0
}

rm -rf /tmp/fakemesh_lck*

MACADDR=""
test -e /usr/share/natcapd/board_mac.lua && MACADDR=$(lua /usr/share/natcapd/board_mac.lua)
test -n "$MACADDR" || MACADDR=$(. /lib/functions/system.sh; get_mac_label | tr a-f A-F)
test -n "$MACADDR" || MACADDR=$(cat /etc/board.json | jsonfilter -e "$['network']['wan']['macaddr']" | tr a-f A-F)
test -n "$MACADDR" || MACADDR=$(cat /etc/board.json | jsonfilter -e "$['network']['lan']['macaddr']" | tr a-f A-F)
test -n "$MACADDR" || MACADDR=$(cat /sys/class/net/eth0/address | tr a-f A-F)
test -n "$MACADDR" || MACADDR=$(cat /sys/class/net/eth1/address | tr a-f A-F)
test -n "$MACADDR" || MACADDR=$(head -c6 /dev/urandom | hexdump -e '/1 "%02X:"' -n6 | head -c17)
test -n "$MACADDR" || MACADDR=$(head -c6 /dev/random | hexdump -e '/1 "%02X:"' -n6 | head -c17)

# --- ZONA DE CREACIÓN DE INTERFACES 2g/5g/6g ---
for band in 2g 5g 6g; do
	wbandstr=$(uci show wireless | grep .band=\'${band}\'$ -m1)
	if test -n "$wbandstr"; then
		radio=$(echo $wbandstr | cut -d\. -f2)
		case "$band" in
			2g) iface_idx=0 ;;
			5g) iface_idx=1 ;;
			6g) iface_idx=2 ;;
		esac
		mesh_iface="meshx${iface_idx}"

		uci set wireless.${mesh_iface}=wifi-iface
		uci set wireless.${mesh_iface}.device="${radio}"
		uci set wireless.${mesh_iface}.network="${mesh_iface}"
		uci set wireless.${mesh_iface}.ifname="${mesh_iface}"
		uci set wireless.${mesh_iface}.mode='ap'
		uci set wireless.${mesh_iface}.wds='1'
		uci set wireless.${mesh_iface}.ssid="${Xid}"
		uci set wireless.${mesh_iface}.hidden='1'
		uci set wireless.${mesh_iface}.wpa_group_rekey='601'
		uci set wireless.${mesh_iface}.max_inactivity='301'
		if test -n "${Xkey}"; then
			uci set wireless.${mesh_iface}.encryption='psk2'
			uci set wireless.${mesh_iface}.key="${Xkey}"
		else
			uci set wireless.${mesh_iface}.encryption='none'
		fi
		if [ "$fronthaul_disabled" = "1" ]; then
			uci set wireless.${mesh_iface}.disabled='1'
		else
			uci delete wireless.${mesh_iface}.disabled 2>/dev/null
		fi

		# Ajuste específico para 6g: htmode/ehtmode
		if [ "$band" = "6g" ]; then
			htmode=$(uci get wireless.${radio}.htmode 2>/dev/null)
			if [ "$htmode" = "HE320" ]; then
				uci set wireless.${radio}.htmode="HE160"
			elif [ "$htmode" = "HE160" ]; then
				uci set wireless.${radio}.htmode="HE80"
			elif [ "$htmode" = "EHT320" ]; then
				uci set wireless.${radio}.htmode="EHT160"
			elif [ "$htmode" = "EHT160" ]; then
				uci set wireless.${radio}.htmode="EHT80"
			fi
		fi

		# Red y DHCP para meshxX
		if [ "$band" = "6g" ]; then
			uci set dhcp.meshx2=dhcp
			uci set dhcp.meshx2.ignore='1'
			uci set network.meshx2=interface
			uci set network.meshx2.device="$(uci get network.lan.device)"
			uci set network.meshx2.proto='dhcp'
			uci set network.meshx2.defaultroute='1'
			uci set network.meshx2.metric='20'
			uci set network.meshx2.hostname="MESH-AGENT6G_$(echo -n $MACADDR | sed 's/://g' | tr a-f A-F)"

			uci set network.meshx2_6=interface
			uci set network.meshx2_6.proto='dhcpv6'
			uci set network.meshx2_6.device='@meshx2'
			uci set network.meshx2_6.reqaddress='try'
			uci set network.meshx2_6.reqprefix='auto'
			uci set network.meshx2_6.delegate='0'
			uci set network.meshx2_6.hostname="MESH-AGENT6G_$(echo -n $MACADDR | sed 's/://g' | tr a-f A-F)"
		fi

		lan_idx=0
		while uci get firewall.@zone[$lan_idx] &>/dev/null && [ $(uci get firewall.@zone[$lan_idx].name) != "lan" ]; do lan_idx=$((lan_idx+1)); done
		lan_net="$(uci get firewall.@zone[$lan_idx].network 2>/dev/null)"
		newlan_net=$(for ln in $lan_net meshx0 meshx0_6 meshx2 meshx2_6; do echo $ln; done | sort | uniq)
		newlan_net=$(echo $newlan_net)
		[ "$lan_net" != "$newlan_net" ] && {
			uci delete firewall.@zone[$lan_idx].network &>/dev/null
			for ln in $newlan_net; do
				uci add_list firewall.@zone[$lan_idx].network="$ln"
			done
			uci commit firewall
		}
	fi
done

# === FIN MESH 6G PARTE 3 ===

# === MESH 6G PARTE 4 ===

agent_sync_config()
{
	[ "$sync_ac" = "1" ] || {
		return 0
	}
	[ "$role" = "wap" ] && {
		rm -rf /tmp/fakemesh_lck2*
	}

	mkdir /tmp/fakemesh_lck3 || return 0
	pid=$$
	touch /tmp/fakemesh_lck3/$pid

	logger -t fakemesh "agent_sync_config($pid): started!"

	touch /tmp/fakemesh.ac.config
	ln -s /tmp/fakemesh.ac.config /etc/config/fakemeshac 2>/dev/null

	while :; do
		[ "$role" != "controller" ] && {
			if test $lost_ac -gt 2; then
				ubus call network.interface.meshx0 down
				sleep 1
				ubus call network.interface.meshx0 up
				sleep 1
			fi
			ubus -t 15 wait_for network.interface.meshx0
		}
		sleep 15
		achost=controller.fakemesh
		if [ "$role" != "controller" ]; then
			if test $lost_ac -gt 0; then
				/etc/init.d/umdns reload
				sleep 5
			fi
			achost="$(ubus call umdns browse | jsonfilter -e "@['_fakemesh_${Xid}._tcp'][*]['ipv4']")"
			if ! test -n "$achost"; then
				logger -t fakemesh "agent_sync_config($pid): umdns: achost not found(lost_ac=$lost_ac)!"
				achost=controller.fakemesh
			fi
			acnum=$(echo -n "$achost" | wc -w)
			if [ "$acnum" -gt 1 ]; then
				logger -t fakemesh "agent_sync_config($pid): umdns: achost found $acnum($achost)(lost_ac=$lost_ac)!"
				rand=$(hexdump -e '"%u"' -n1 /dev/urandom)
				rand=$(((rand % acnum) + 1))
				achost=$(for w in $achost; do echo $w; done | head -n$rand | tail -n1)
				logger -t fakemesh "agent_sync_config($pid): umdns: achost found random select($achost)(lost_ac=$lost_ac)!"
			fi
		fi

		hash=$(echo -n ${Xid}${Xkey} | md5sum | head -c32)
		if ( \
		[ "$role" = "controller" ] && cp /etc/config/fakemesh /tmp/fakemesh.ac.config.tmp || \
		timeout 10 wget -4 -qO /tmp/fakemesh.ac.config.tmp http://$achost/fakemesh.$hash 2>/dev/null ); then
			:
		else
			lost_ac=$((lost_ac+1))
			logger -t fakemesh "agent_sync_config($pid): fetch config from $achost failed($lost_ac)!"
			acip=$(ip route | grep "default via" -m1 | awk '{print $3}')
			if test -n "$acip" && ifconfig br-lan | grep -q "addr:$acip "; then
				logger -t fakemesh "agent_sync_config($pid): acip=$acip is setup on br-lan(lost_ac=$lost_ac)!"
				ubus call network.interface.lan down
				/etc/init.d/network reload
				sleep 5
			fi
			if test -n "$acip" && [ "$role" != "controller" ] && timeout 5 wget -4 -qO /tmp/fakemesh.ac.config.tmp http://$acip/fakemesh.$hash 2>/dev/null; then
				logger -t fakemesh "agent_sync_config($pid): fetch config from gateway($acip) ok(lost_ac=$lost_ac)"
			elif test -n "$achost" && [ "$role" != "controller" ] && timeout 5 wget -4 -qO /tmp/fakemesh.ac.config.tmp http://$achost/fakemesh.$hash 2>/dev/null; then
				logger -t fakemesh "agent_sync_config($pid): fetch config from achost($achost) ok(lost_ac=$lost_ac)"
			else
				if test $lost_ac -ge $LOST_AC_CNT; then
					lost_ac=$lost_ac exec /usr/sbin/fakemesh agent_lost_ac &
					return 0
				fi
				logger -t fakemesh "agent_sync_config($pid): fetch config from achost($achost)/gateway($acip) failed($lost_ac), wait 30s"
				sleep 30
				rm -f /tmp/fakemesh.ac.config.tmp
				test -f /tmp/fakemesh_lck3/$pid || return 0
				continue
			fi
		fi

		if ! grep -q fakemesh /tmp/fakemesh.ac.config.tmp; then
			rm -f /tmp/fakemesh.ac.config.tmp
			test -f /tmp/fakemesh_lck3/$pid || return 0
			continue
		fi

		mv /tmp/fakemesh.ac.config.tmp /tmp/fakemesh.ac.config

		test $lost_ac -gt 0 && logger -t fakemesh "agent_sync_config($pid): fetch config ok!"

		oldbsh=$(uci get fakemesh.default.band_steer_helper || echo none)
		newbsh=$(uci get fakemeshac.default.band_steer_helper || echo none)
		[ "${oldbsh}" = "${newbsh}" ] || {
			uci set fakemesh.default.band_steer_helper="${newbsh}"
			uci commit fakemesh
			band_steer_helper="${newbsh}" exec /usr/sbin/fakemesh band_steer_helper_switch &
		}

		oldcfgmd5=$(uci get fakemesh.default.wifim_md5 2>/dev/null)
		newcfgmd5=$(uci show fakemeshac | grep "^fakemeshac.@wifim" | md5sum | head -c 32)
		[ "${oldcfgmd5}" = "${newcfgmd5}" ] || {
			logger -t fakemesh "agent_sync_config($pid): config change!"
			I=0
			while uci get wireless.@wifi-iface[$I] &>/dev/null; do
				if uci show wireless.@wifi-iface[$I] | grep -q wireless.meshx[012]=wifi-iface; then
					I=$((I+1))
					continue
				fi
				uci delete wireless.@wifi-iface[$I] &>/dev/null
			done

			J=0
			K=0
			while uci get fakemeshac.@wifim[$J] &>/dev/null; do
				ssid=$(uci get fakemeshac.@wifim[$J].ssid)
				encryption=$(uci get fakemeshac.@wifim[$J].encryption)
				key=$(uci get fakemeshac.@wifim[$J].key)
				bands=$(uci get fakemeshac.@wifim[$J].band)
				enabled=$(uci get fakemeshac.@wifim[$J].enabled || echo 1)

				[ "$bands" = "2g5g" ] && bands="2g 5g"
				[ "$bands" = "2g6g" ] && bands="2g 6g"
				[ "$bands" = "5g6g" ] && bands="5g 6g"
				[ "$bands" = "2g5g6g" ] && bands="2g 5g 6g"

				[ "$enabled" = "1" ] && {
					for band in $bands; do
						for wbandstr in $(uci show wireless | grep .band=\'${band}\'$); do
						if test -n "$wbandstr"; then
							radio=$(echo $wbandstr | cut -d\. -f2)
							uci set wireless.wifinet$K=wifi-iface
							uci set wireless.wifinet$K.device="${radio}"
							if [ "$role" = "controller" ]; then
								uci set wireless.wifinet$K.network='lan'
							else
								uci set wireless.wifinet$K.network="meshx0"
							fi
							uci set wireless.wifinet$K.mode='ap'
							uci set wireless.wifinet$K.ssid="${ssid}"
							uci set wireless.wifinet$K.wpa_group_rekey='601'
							uci set wireless.wifinet$K.max_inactivity='301'
							if [ "${encryption}" != "none" ]; then
								uci set wireless.wifinet$K.encryption="${encryption}"
								uci set wireless.wifinet$K.key="${key}"
							else
								uci set wireless.wifinet$K.encryption='none'
							fi
							if uci get wireless.${radio}.path | grep -q bcma || iwinfo wlan${radio:5} info | grep -qi Cypress; then
								WLAN_IDX=${radio:5}
								uci set wireless.wifinet$K.ifname="wlan${WLAN_IDX}"
							else
								uci set wireless.wifinet$K.ieee80211r='1'
								uci set wireless.wifinet$K.ft_over_ds='1'
								uci set wireless.wifinet$K.ft_psk_generate_local='1'
							fi
							if opkg list-installed 2>/dev/null | grep -q wpad-basic || apk list 2>/dev/null | grep wpad-basic | grep -q installed; then
								:
							else
								uci set wireless.wifinet$K.bss_transition='1'
								uci set wireless.wifinet$K.wnm_sleep_mode='1'
								uci set wireless.wifinet$K.time_advertisement='2'
								uci set wireless.wifinet$K.time_zone='GMT0'
								uci set wireless.wifinet$K.ieee80211k='1'
								uci set wireless.wifinet$K.rrm_neighbor_report='1'
								uci set wireless.wifinet$K.rrm_beacon_report='1'
							fi

							K=$((K+1))
						fi
						done
					done
				}

				J=$((J+1))
			done

			uci set fakemesh.default.wifim_md5="${newcfgmd5}"

			uci commit fakemesh
			uci commit wireless
			/etc/init.d/network reload &
		}

		test -f /tmp/fakemesh_lck3/$pid || return 0

		if test $lost_ac -ge $LOST_AC_CNT; then
			logger -t fakemesh "agent_sync_config($pid): recovery from lost_ac=$lost_ac!"
			sleep 5
			/etc/init.d/network reload
			/etc/init.d/dnsmasq reload
			nft list tables 2>/dev/null | grep 'table netdev brmeshfilters_' | while read tb; do
				nft delete $tb
			done
			test -x /etc/init.d/umdns && /etc/init.d/umdns reload
			test -x /etc/init.d/dawn && /etc/init.d/dawn restart
		fi
		lost_ac=0

		rand=$(hexdump -e '"%u"' -n1 /dev/urandom)
		sleep $((50+(rand+0)%20))
		test -f /tmp/fakemesh_lck3/$pid || return 0
	done

	rm -f /tmp/fakemesh_lck3/$pid; rmdir /tmp/fakemesh_lck3
}

# === FIN MESH 6G PARTE 4 ===

# === MESH 6G PARTE 5 ===

agent_keep_alive()
{
	[ "$role" = "agent" ] || return 0

	sta_lost=0

	wbandstr=$(uci show wireless | grep .band=\'${band}\'$ -m1)
	radio=$(echo $wbandstr | cut -d\. -f2)
	channel=$(uci get wireless.${radio}.channel)
	test -n "$channel" || return 1

	mkdir /tmp/fakemesh_lck2 || return 0
	pid=$$
	touch /tmp/fakemesh_lck2/$pid

	logger -t fakemesh "agent_keep_alive($pid): started!"
	while :; do
		sleep 10
		sta="$(ubus -S list wpa_supplicant.meshx1)"
		if test -n "$sta"; then
			if [ $(iwinfo meshx1 info | grep -c 'ESSID: unknown') -ge 1 ]; then
				sta_lost=$((sta_lost+1))
				if [ "$sta_lost" -ge 3 ]; then
					logger -t fakemesh "agent_keep_alive($pid): Agent lost connection!"
					rm -f /tmp/fakemesh_lck2/$pid; rmdir /tmp/fakemesh_lck2
					exec /usr/sbin/fakemesh agent_fix_channel &
					return 0
				fi
			elif [ "$(iwinfo meshx1 info | head -n3 | tail -n1 | awk '{print $4}')" != "$channel" ]; then
				logger -t fakemesh "agent_keep_alive($pid): Agent channel changed!"
				rm -f /tmp/fakemesh_lck2/$pid; rmdir /tmp/fakemesh_lck2
				exec /usr/sbin/fakemesh agent_fix_channel &
				return 0
			fi
		fi
		sleep 30
		test -f /tmp/fakemesh_lck2/$pid || return 0
	done

	rm -f /tmp/fakemesh_lck2/$pid; rmdir /tmp/fakemesh_lck2
}

agent_fix_channel()
{
	exec /usr/sbin/fakemesh agent_sync_config &

	[ "$role" = "agent" ] || return 0

	wbandstr=$(uci show wireless | grep .band=\'${band}\'$ -m1)
	radio=$(echo $wbandstr | cut -d\. -f2)
	channel=$(uci get wireless.${radio}.channel)
	test -n "$channel" || return 1

	mkdir /tmp/fakemesh_lck1 || return 0
	pid=$$
	touch /tmp/fakemesh_lck1/$pid

	logger -t fakemesh "agent_fix_channel($pid): started!"
	while :; do
		sleep 10
		sta="$(ubus -S list wpa_supplicant.meshx1)"
		if test -n "$sta"; then
			chan=$(iwinfo meshx1 scan | grep -A1 -B1 "ESSID: \"${Xid}\"" | head -n3 | tail -n1 | grep -io "Channel:.*"| awk '{print $2}')
			if test -n "$chan"; then
				if [ "$chan" != "$channel" ]; then
					logger -t fakemesh "agent_fix_channel($pid): Setting up channel ($chan) for ${radio}"
					uci set wireless.${radio}.channel="$chan"
					test "$chan" -ge "36" -a "$chan" -le "44" || {
						htmode=$(uci get wireless.${radio}.htmode 2>/dev/null)
						if [ "$htmode" = "VHT160" ]; then
							uci set wireless.${radio}.htmode="VHT80"
						elif [ "$htmode" = "HE160" ]; then
							uci set wireless.${radio}.htmode="HE80"
						fi
					}
					uci commit wireless
					/etc/init.d/network reload &
				fi
				logger -t fakemesh "agent_fix_channel($pid): Channel ($chan) for ${radio} ready!"
				break
			fi
		fi
		sleep 20
		test -f /tmp/fakemesh_lck1/$pid || return 0
	done

	rm -f /tmp/fakemesh_lck1/$pid; rmdir /tmp/fakemesh_lck1

	exec /usr/sbin/fakemesh agent_keep_alive &
}

# === FIN MESH 6G PARTE 5 ===
